version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes

  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: elk-es
#    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
      # 指定单节点启动
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es:/usr/share/elasticsearch
    ports:
      - "9200:9200"
  kibana:
    image: kibana:8.10.4
    container_name: elk-kibana
#    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elk-es:9200
      I18N_LOCALE: zh-CN
    ports:
      - "5601:5601"


volumes:
  rabbitmq:
  redis:
  es:
networks:
  default:
    driver: bridge