version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      -  nacos-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "7848:7848"
      - "9849:9849"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./image/MysqlDockerfile
    image: example/mysql:8.0.30
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_nacos:/var/lib/mysql
    ports:
      - "3326:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_nacos:
  nacos-logs: